import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { computeIntegratedLoudness } from '../loudnessComputation';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURES = resolve(__dirname, 'fixtures/loudness');

/**
 * Minimal PCM WAV reader for 16-bit little-endian fixtures generated by ffmpeg.
 */
function readWavPcm16(path: string): {
	channels: Float32Array[];
	sampleRate: number;
} {
	const buf = readFileSync(path);
	const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);

	let offset = 12;
	let numChannels = 0;
	let sampleRate = 0;
	let bitsPerSample = 0;
	let dataOffset = 0;
	let dataSize = 0;

	while (offset + 8 <= buf.length) {
		const id = buf.toString('ascii', offset, offset + 4);
		const size = view.getUint32(offset + 4, true);

		if (id === 'fmt ') {
			numChannels = view.getUint16(offset + 10, true);
			sampleRate = view.getUint32(offset + 12, true);
			bitsPerSample = view.getUint16(offset + 22, true);
		} else if (id === 'data') {
			dataOffset = offset + 8;
			dataSize = size;
			break;
		}

		offset += 8 + size + (size % 2);
	}

	if (bitsPerSample !== 16) {
		throw new Error(`Expected 16-bit PCM, got ${bitsPerSample}`);
	}

	const frameCount = dataSize / (2 * numChannels);
	const channels: Float32Array[] = Array.from(
		{ length: numChannels },
		() => new Float32Array(frameCount)
	);

	let p = dataOffset;
	for (let i = 0; i < frameCount; i++) {
		for (let c = 0; c < numChannels; c++) {
			channels[c][i] = view.getInt16(p, true) / 32768;
			p += 2;
		}
	}

	return { channels, sampleRate };
}

/**
 * Ground-truth `input_i` from `ffmpeg -af loudnorm=print_format=json`.
 * Regenerated alongside the WAV fixtures in fixtures/loudness/.
 */
const FFMPEG_INPUT_I: Record<string, number> = {
	'stereo_44100.wav': -20.36,
	'mono_44100.wav': -23.38,
	'stereo_48000.wav': -20.36,
	'limited_master.wav': -14.77,
	'quiet_mix.wav': -32.36,
	'mono_48000.wav': -23.38,
};

describe('computeIntegratedLoudness vs ffmpeg loudnorm', () => {
	for (const [file, expected] of Object.entries(FFMPEG_INPUT_I)) {
		it(`agrees within ±0.1 LU on ${file}`, () => {
			const { channels, sampleRate } = readWavPcm16(resolve(FIXTURES, file));
			const result = computeIntegratedLoudness(channels, sampleRate);

			expect(result.integratedLufs).toBeGreaterThan(-70);
			expect(Math.abs(result.integratedLufs - expected)).toBeLessThan(0.1);
		});
	}

	it('confirms mono vs dual-mono ~3 LU gap matches ffmpeg', () => {
		const mono = FFMPEG_INPUT_I['mono_44100.wav'];
		const stereo = FFMPEG_INPUT_I['stereo_44100.wav'];
		// ffmpeg itself reports ~3 LU between mono and stereo of the same content.
		expect(stereo - mono).toBeCloseTo(3.01, 1);
	});
});
